### ISSUE TITLE
Plugins are getting less results in new code

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#112]
I was going to update the repeat-api on GCloud tonight, but I'm not seeing good results from the plugins using the new updated code that I was seeing on the old plugins that're still on G Cloud.  I think there needs to be some quality checking on the new plugin code before I update the G Cloud cloud.

Examples:

1. This paper shows a result under Data Mining and Data Analysis, but when I upload it locally onto the updated plugins, there's no results.
http://demo.ripeta.com/#!/paper-view/4
[journal.pone.0181173.pdf](https://github.com/ripeta/repeat-aft/files/1813632/journal.pone.0181173.pdf)

2. This one has results under 3 categories on the old plugins and only one in new (biblio).  
And biblio results for old were DOI and funding, on new the biblio results are funding and grantid
http://demo.ripeta.com/#!/paper-view/32
[1-101.pdf](https://github.com/ripeta/repeat-aft/files/1813656/1-101.pdf)

**Comment by DragonWriter** [comment]
1. Previous didn't have any biblio data either, so nothing different there. Analysis_sw should have been picked up with filter r'data.*?(cleaned|validated|excluded)' (specifically 'excluded'). Text_nlp_yn shouldbe picked up by filter r'natural language.*?processing'. And for analysis_process_clear it should have first picked up by the first filter with 'analysis' then the second with 'following'.

2. So the new one doesn't return a result for DOI, because I don't think that was changed? At least it got grant_id. Looking at the result returned previously for data_cleaned the newer algorithm should have picked it up by filter 'excluded.*?data'. Similarly analysis_sw should have picked it up with filter r'analys(is|es).*?software' (specifically 'analyses.*?software' option). And lastly analysis_process_clear should be picked up first by filter 'analysis' then by the secondary filter option 'following'.

This leads me to believe perhaps the new code is not properly accessing the right plugins maybe? I am looking at the code in the repeat-plugins repo for the above analysis. Either that or you have the two versions flipped somehow?

**Comment by ejcramer** [comment]
You're right, sorry to waste your time.  I was still in mode from testing the merge and was not using the private repeat-plugins repo.  The results are much better.  I'm still not sure why it's not gettng the DOI on the second article, but I'll do a diff on the plugin when I get on the server.

![image](https://user-images.githubusercontent.com/1063909/37452664-9ce2a2f2-280b-11e8-9eda-660981b2fd82.png)
