### ISSUE TITLE
Potential Data Copy Tool

### ISSUE THREAD

**Issue by DragonWriter** [ripeta/repeat-aft#134]
Want to create a script that copies all the papers and user_values (optionally, also extracted_values) from one target url to another target url, assuming they have a similar django model structure.

For instance could copy all the data from data from data.ripeta.com to a fresh local version.
Might also help for some testing, whenever a new version is made.

By default would copy all papers, with options for using a given list, or limit to a maximum number of papers.

**Comment by DragonWriter** [comment]
Script is running and committed. Next updates to this are to be able to pass in a list of specific paper ids to extract, as well as save the paper mapping to a file.

**Comment by cmw48** [comment]
Proposing enhanced datacopy feature set (review for team programming):
- on command line, user can specify either a single paper or a list of individual papers for data copy
- consider adding a switch and arg for writing the output json to a file instead of to a target url
- consider reverse of above - add an arg to read from json file and write to target url

**Comment by DragonWriter** [comment]
datacopyv2.py was updated to add the ability of adding a list of papers either as a string within the command or in a text file. Allows blanks to be added to pad paper ids.
Examples of use:
`python datacopyv2.py --paperlist 1,2,,4`
`python datacopyv2.py --paperlist paper_ids.txt`
It was also updated to use a local config.json file for the settings that it now shares with cleanup.py.
