### ISSUE TITLE
using struct_text for article_doi

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#135]
We have good identifiers from the struct_text.  I'm wondering if it would be a good idea to have the article_doi plugin use the identifier(s) from struct_text and the existing NLTK/regex similar to article_title and article_authors.

If there is more than one identifier, do we create a semi-colon string like authors?

**Comment by ejcramer** [comment]
Leaving to discuss.  Should probably be the same as title, author, and identifier.

**Comment by DragonWriter** [comment]
Added in most recent commit to model-test branch of repeat-plugins and repeat-aft.  Changes take the form of two new variable mode options: 'text' and 'struct_text'. For the variables, article_doi, article_title, and article_authors if the variable's mode is set to 'struct_text' then it will retrieve a value from the structured text if available, otherwise it will not. The 'text' option is not required in the otherwise case but is there for either potential future use or for to specify source_detail (currently the case for article_doi).

This brought up the possibility of turning the variable.mode field into a regular text field without options for more flexibility for changing or adding new modes in the future, but that will be added as a separate issue.

**Comment by ejcramer** [comment]
When I went to change the plugin_mode for the article_* variables to use "struct_text", I got an error that "struct_text" was not a choice for plugin_mode.  On my local install, I added it in models.py as a "mode_choices" and then I could change and seems to work.  I wasn't sure what all the choices were supposed to be, so am hoping you'll take a look and correct as needed. Please and thanks!

**Comment by ejcramer** [comment]
Accidently closed.

**Comment by DragonWriter** [comment]
Looks like I forgot to commit the mode_choice additions. Will do so soon.
Aside from that, I was able to replicate the issue and working out on troubleshooting it.

**Comment by DragonWriter** [comment]
Latest commit to nc-test addresses both of these problems (mode choices and struct_text not working).
