### ISSUE TITLE
Cloud hosting for back-end and front-end

### ISSUE THREAD

**Issue by siddharthist** [ripeta/repeat-aft#27]

**Comment by ejcramer** [comment]
Would like to evaluate Google Cloud, AWS, and Heroku for hosting.  Not sure about NixOps.

**Comment by ejcramer** [comment]
* pythonanywhere: unable to resolve CORS issue after valient effort
* heroku: unable to resolve db issues (doesn't work with sqlite, tried postgres, needs more troubleshooting at some point)
* google cloud app: free standard/flex have python/pip version issues
* WORKED: google cloud compute (virtual host): set up dev environment, implemented repeat-aft, firewall issues resolved, pdf issues resolved. $15/month with low level VH, prob more like $35 for prod.

* Needs to be moved to ripeta google acct (in mine).  Could change to postgres with the production account.

**Comment by ejcramer** [comment]
9 am EST Hangouts with Preston (rep) and Chris (dev) at Google Cloud re using them for Ricochet.

Questions/discussion
- App engine vs Compute Engine (version and need for client front-end hosting) - feedback given
- Pricing and scaling (CPU, disks, etc) - auto scaler, managed instance groups, bronze support - forum, silver $150/month, gold $250/month.
- DNS and static IP - should be no issue
- IAM - Google App (G Suite) - what happens when added? Manage perms via G Suite.
- Backup vs snapshot: Is there a limit on number, space, or time on snapshots. Getting back to me.
- File storage for documents? fuse adapter, cloud functions - serverless computing options (beta) - sending docs.

They are sending specific docs to me and we'll setup another meeting to discuss pricing in more detail with an additional rep.

**Comment by ejcramer** [comment]
The GCloud is setup and permissions given to Leslie.  I'm updating the documentation with specifics at:
http://repeat-aft.readthedocs.io/en/latest/administrators/cloud-server.html

**Comment by ejcramer** [comment]
Google Cloud - Compute Engine
https://cloud.google.com/compute/docs/access/user-accounts/

Backend code - Python Django Framework
/usr/local/environments/repeat-aft

Frontend code - AngularJS in apache
/var/www/html ->/usr/local/environments/repeat-bow/app

Postgresql
/usr/lib/postgresql/9.5
Will send postgres password in privnote

Database backup directories
/usr/local/backups
