### ISSUE TITLE
Store extracted data in table

### ISSUE THREAD

**Issue by cynhudson** [ripeta/repeat-aft#72]
Extracted data does seem to be stored in any table in the database - only user entered variables.

**Comment by DragonWriter** [comment]
Resolved and merged with master. Plugins now return data in the form of (value_text, value_result, source_type, source_detail) rather than the previous (value_result, value_text) equivalent. This data is used to update the DB in analysis.py by inserting the new value unless an almost exact duplicate (only different fields being the 2 recently added date fields) exists already in the DB.
