### ISSUE TITLE
api_paper.authors should be a list of authors not a string

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#92]
Prior to recent model changes, the api had authors as a list/array and it would not accept strings.  Now it appears from that data to be a string.  I believe the team wants the authors to be a list.

models.py shows it configured to be a list (see below).  More research needed.

Past:
{
    "unique_id": "doi:12345",
    "title": "Testing authors",
    **"authors": "['Yo Yo Ma', 'No No Ma']",**
    "document": "http://35.185.114.189:8000/api/v0/papers/pdf/2017/11/03/test1_17PXkuq.pdf",
    "document_text": null,
    "domains": [
        "core"
    ]
}

Current:
{
    "id": 56,
    "identifier": "",
    "document": "http://localhost:8000/api/v0/pdf/2017/11/03/test2_z2EwajF.pdf",
    "document_text": null,
    "title": "Testing on new code",
    **"authors": "Yo Yo Ma, No No Ma",**
    "createdDate": "2017-11-03T16:44:37.429748Z",
    "domains": [
        "core"
    ]
}

models.py says it's a list:
    authors = jsonfield.JSONField(**{
        "default": list,
        "max_length": 10000,
        "blank": True,
        "null": True,
        "help_text": "Authors of the paper"
    })

**Comment by DragonWriter** [comment]
So this is in the papers object where the authors are no longer a required field as they are going to be stored in a value.  I can change the authors field in paper to a jsonfield, which works for lists pretty easily.  However, if we want to end up using the entry in the value table maybe we want to consider making the same change to value_result (make it a jsonField). An alternative is to keep it as a string but format it so that it's a bracketed, easily-parsable list and then add in a built in function that parses/constructs it as a list correctly when it's retrieved.

**Comment by ejcramer** [comment]
Good point about the api_value:'article_authors'.value_text replacing the api_paper.authors.  I'm still not sure on when or if we will deprecate those api_paper fields.  I think we'll want them around until we have fairly reliable plugin results.

I **_think_** we should change api_paper.authors to a jsonfield.  

I like the idea of the api_value.value_text being a string and formatting it. Seems like the article_authors plugin will need to parse authors into some sensible format regardless. 

Thinking like a front end client, it also needs to be clear how to send user input for article_authors, e.g. csv? (documentation).

**Comment by DragonWriter** [comment]
Okay, so I'll change papers.authors to a jsonfield.  And then add a function to value called get_as_list that'll parse the value_result string and return it. Think it'd be simplest to just treat it as a csv and just convert the csv to a list.

**Comment by DragonWriter** [comment]
Okay, didn't realize/forgot that even currently the authors is a jsonField. And is a list by default, though it seems some additional work needs to be put in so that when data is entered into it's added properly.

**Comment by ejcramer** [comment]
Need to keep in mind that the data may have grammatical comma's.

**Comment by DragonWriter** [comment]
Fixed in commit [small updates to django fields and small additions for repeat_ml](https://github.com/ripeta/repeat-aft/commit/cc6ea0b8d5b27865f34537588fbf42622a6b51ec) by changing the paper.author field from a jsonField to a textField , to match the the same format as the value.valute_text field, where it can be returned as a list.

Note the get_as_list option could potentially be changed to split only by semicolon (right now both work), to account for the potential of having comma-separated titles in authors list. So the author string text should probably be formatted by separating authors by semicolons.
